### ISSUE TITLE
Would like to add solutions to leetcode problems based on graph and linked lists

### ISSUE THREAD

**Issue by pri1311** [reyadussalahin/problem-solving#26]
Would like to provide C++ solutions

**Comment by reyadussalahin** [comment]
@pri1311, at first thanks for you interest and welcome to the community. You have to go through the following steps to contribute to this repository.

1. At first create a fork.
2.After that, read the pull request guidelines: [pull request template](https://github.com/reyadussalahin/problem-solving/blob/main/.github/PULL_REQUEST_TEMPLATE.md).
3. Add the problem's solution that you want. You must follow the contributing guidelines (specially, the structure of categories and subcategories) explained [here](https://github.com/reyadussalahin/problem-solving/blob/main/.github/CONTRIBUTING.md).

It's a very easy procedure. If you have any problem understanding about anything or got stuck in a step, just mail me at [reyadussalahin@gmail.com](mailto:reyadussalahin@gmail.com)

We'll be waiting for your pull request.

Also, there is a [discussion section](https://github.com/reyadussalahin/problem-solving/discussions) here. You can discuss anything in the discussions section.

**Comment by phase7** [comment]
> Would like to provide C++ solutions

Welcome to our community! Looking forward to see your contribution.

**Comment by reyadussalahin** [comment]
fixed in pr #27
